server:
  port: 8081
  address: 0.0.0.0
  servlet:
    session:
      timeout: 1m
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manager?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 0.chenjie
    continue-on-error: true
    initialization-mode: always
    schema:
      - classpath:sql/schema.sql
    data:
      - classpath:sql/data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
logging:
  level:
    com.roje.web.server: debug