server:
  port: 8081
  address: 0.0.0.0
  servlet:
    session:
      timeout: 1m
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manager?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 0.chenjie
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect:
          storage_engine: innodb
logging:
  level:
    com.roje.web.server: debug